Feature/issue 112
onetop21/MLAppDeploy pull request #126
Opened 2021-11-08 02:35 UTC by kkkdeon

Resolve #112 
Resolve #122 

- deploy시 project key 변경
- app kind -> Job / Service 변경
  - 현재 validator schema 에 따라 advanced가 아닌 Job과 Service를 AppJob /AppService라는 이름으로 모델을 별도로 지정했습니다.

2021-11-08 03:08 UTC, JunhoeKim requested changes

2021-11-08 03:08 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +                config_labels['MLAD.PROJECT.SERVICE.CONTROLLER'] = 'Job'
이 property는 현재쓰는 곳이 없고 'MLAD.PROJECT.SERVICE.KIND'에 종속적인 것 같은데 굳이 등록할 필요가 있나요?

2021-11-08 12:25 UTC, kkkdeon commented on python/mlad/cli/deploy.py
> +    base_key = utils.project_key(workspace)
이거 사용하는 데가 꽤 되는데 지금 바꾸는게 좋을까요?

2021-11-08 12:26 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +                config_labels['MLAD.PROJECT.SERVICE.CONTROLLER'] = 'Job'
kind로 판단하도록 바꿨습니다

2021-11-08 15:32 UTC, JunhoeKim commented on python/mlad/cli/deploy.py
> +    base_key = utils.project_key(workspace)
9군데 정도 되는데 바꾸는 비용이 크지는 않을 것 같아요!

2021-11-09 06:50 UTC, JunhoeKim approved these changes

2021-11-09 06:52 UTC, merged