mlad deploy update 기능 추가
onetop21/MLAppDeploy pull request #145
Opened 2021-11-17 09:19 UTC by kkkdeon

Resolve #125 

**api**
1. deploy serve 시 project yaml을 annotation에 저장 (namespace annotation)
- 아직 train up할 때는 project yaml 저장하지 않도록 optional로 두었습니다. 
2. project update api 추가
- 바뀐 project yaml로 annotation을 업데이트하고
- deployment를 rollout 합니다. 

**cli** (mlad update = mlad deploy update)
mlad deploy update {project-key}
mlad deploy update {project-key} -f {update file}
- 현재 project yaml과 update 적용할 yaml 의 diff를 확인하고 diff가 존재할 경우 api request
  -  schema diff 확인을 위해 Dictdiffer 패키지 사용
  - 유효하지 않은 option에 변경이 생길 경우 error
    - 변경 가능한 option : ['image', 'command', 'args', 'scale', 'env', 'quota']

**test**
1. mlad serve
2. project file 임의 변경
3. mlad deploy update {project-key}
4. (k8s) `kubectl rollout history` 로 rollout 내용 확인 및 `describe`로 변경 사항 확인

2021-11-17 10:30 UTC, JunhoeKim requested changes

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/cli/deploy.py
> +    lines = API.project.create(base_labels, extra_envs, project_yaml=project, credential=credential, allow_reuse=False)
project_yaml에 project 값을 넣으면 한 번 가공된 오브젝트가 들어가는건데 괜찮을까요?

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/cli/deploy.py
> +                if key:
여기 if문과 diff type이 add인 경우의 차이가 뭔가요?

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/cli/deploy.py
> +                            diff_schema[name][key] = None
diff_schema[name][key] = None으로 지정하는거는 어떤 효과가 있죠? 뒤의 로직에서 사용하지 않는 것 같아서요 뒤에 update spec을 뽑아낼 때 update_apps를 이용하는게 아니라 diff_schema가 변형되서 갈 수 있는 것 같습니다.

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/cli/deploy.py
> +    for name, value in diff_schema.items():
그리고 변수명들이 너무 일반적이여서 (value 등) 이게 dict인지 어쩐지 예상이 어려워서 코드 가독성이 떨어집니다. 더 명시적인 이름이면 좋을 것 같아요

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +    except config.config_exception.ConfigException as e:
as e는 사용하지 않으면 안붙이는게 맞다고 생각합니다. lint에 걸리기도 하고요

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +    if not isinstance(cli, client.api_client.ApiClient): raise TypeError('Parameter is not valid type.')
indent 내려주세요

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +            current = {env.name : env.value for env in container_spec.env}
이러면 삭제가 반영이 안되지 않나요?

2021-11-17 10:30 UTC, JunhoeKim commented on python/mlad/cli/exceptions.py
> +class ImageNotFoundError(Exception):
이건 위치를 옮기신건가요?

2021-11-18 01:21 UTC, kkkdeon commented on python/mlad/cli/deploy.py
> +    lines = API.project.create(base_labels, extra_envs, project_yaml=project, credential=credential, allow_reuse=False)
가공된 object = default 필드 추가된 상태 말씀하시는 거라면 그게 controller쪽에서 처리하기도 편하고 나중에 dashboard에서 yaml 보여주게되도 그게 맞다고 생각해서 그렇게 했습니다

2021-11-18 01:28 UTC, kkkdeon commented on python/mlad/cli/deploy.py
> +                if key:
add/remove의 경우 (아예 없던 key가 추가되거나 key는 그대로지만 내부 요소가 추가된 경우)/(key가 삭제되거나 내부 요소가 삭제된 경우) 두가지 케이스가 있을 수 있어 그걸 처리하는 부분입니다.
remove의 경우 key 가 삭제되었을 경우 update[key]가 없기 때문에 None으로 저장합니다.

2021-11-18 01:30 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +            current = {env.name : env.value for env in container_spec.env}
원래 env는 append 하기로 하지 않았었나요 ? 그래서 같은 key 에 value 변경된 경우 덮어씌우는 것만 처리하기 위해서 이렇게 했습니다.

2021-11-18 01:32 UTC, kkkdeon commented on python/mlad/cli/exceptions.py
> +class ImageNotFoundError(Exception):
이거는 제가 건드린 기억이 없는데 diff가 뜨네요ㅎㅎ;;원래 이 파일에 있는 거는 맞죠??

2021-11-18 11:22 UTC, JunhoeKim approved these changes

2021-11-18 11:22 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +            current = {env.name : env.value for env in container_spec.env}
delete 반영으로 변경

2021-11-18 11:30 UTC, merged