feat: mlad ls 에 image 삭제 & age 추가
onetop21/MLAppDeploy pull request #165
Opened 2021-11-22 10:04 UTC by kkkdeon

Resolve #148 

- mlad ls age(uptime) 추가
- mlad ls 에서 보여지는 image 가 불필요한 정보라고 판단되어 삭제

2021-11-22 10:15 UTC, JunhoeKim requested changes

2021-11-22 10:15 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +            'uptime': utils.created_to_age(spec['created'])
key가 왜 age가 아니라 update으로 하셨어요?

2021-11-22 10:18 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +        'created': namespace.metadata.creation_timestamp,
이거는 어떤게 변경된건가요??

2021-11-23 01:08 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +        'created': namespace.metadata.creation_timestamp,
datetime -> timestamp 이던걸 그냥 datetime으로 두었습니다

2021-11-23 01:10 UTC, kkkdeon commented on python/mlad/cli/project.py
> +            'uptime': utils.created_to_age(spec['created'])
기존에 status 에서 쓰던 변수명을 따랐습니다 age로 통일할까요??

2021-11-23 01:58 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +            'uptime': utils.created_to_age(spec['created'])
age로 통일합시다!

2021-11-24 04:56 UTC, JunhoeKim approved these changes

2021-11-24 04:59 UTC, merged