feat: project default format 삭제 및 버그 수정
onetop21/MLAppDeploy pull request #262
Opened 2022-01-25 08:26 UTC by kkkdeon

- schema 업데이트
- default format 삭제
- deploy update 버그 수정

cerberus-document-editor 버전 업그레이드된 후에 머지 예정

2022-01-26 01:25 UTC, JunhoeKim requested changes

2022-01-26 01:25 UTC, JunhoeKim commented on python/mlad/cli/train.py
> +    workdir = utils.get_project()['workdir'] \
`utils.get_project()['workdir']` => `project['workdir']` ?

2022-01-26 01:25 UTC, JunhoeKim commented on python/mlad/cli/validator/schema.yaml
> +          oneof:
이렇게 바뀌게된 상황을 설명하실 수 있나요?

2022-01-26 01:25 UTC, JunhoeKim commented on python/mlad/cli/validator/schema.yaml
> +            valuesrules:
이 property는 어떤 뜻인가요?

2022-01-26 01:25 UTC, JunhoeKim commented on python/mlad/cli/validator/validators.py
> +        schema = yaml_parser.load(f)
validators쪽 변경사항도 간단하게 설명해주실 수 있나요?

2022-01-26 05:03 UTC, kkkdeon commented on python/mlad/cli/train.py
> +    workdir = utils.get_project()['workdir'] \
project 기본 정보에는 없고 project['project_yaml']['workdir'] 에 같은 정보가 있긴한데 이걸쓰는게 나을까요?

2022-01-26 05:03 UTC, kkkdeon commented on python/mlad/cli/validator/schema.yaml
> +          oneof:
preps의 요소당 하나의 schema(run/add/pip...중) 만 가능하게 하는 옵션입니다. preps[0] = {'run':'', 'pip:''} 같은 경우를 방지합니다

2022-01-26 05:03 UTC, kkkdeon commented on python/mlad/cli/validator/schema.yaml
> +            valuesrules:
label dict의 value 가 string이라는 의미입니다 이 옵션이 없으면 editor에서 label의 schema 판단이 불가한 이슈가 있습니다

2022-01-26 09:06 UTC, JunhoeKim commented on python/mlad/cli/train.py
> +    workdir = utils.get_project()['workdir'] \
네 그게 더 의미에 맞는 것 같습니다. 그럴 일은 없겠지만 중간에 project file의 workdir이 변경되거나하면 난감한 상황이 발생 할 수 있을 것 같아서요

2022-01-26 09:14 UTC, JunhoeKim commented on python/mlad/cli/validator/schema.yaml
> +          oneof:
아하 cerberus_kind 기능이낙요? 아니면 cerberus 기능인가요?

2022-01-27 01:33 UTC, kkkdeon commented on python/mlad/cli/validator/schema.yaml
> +          oneof:
cerberus기능입니다

2022-01-27 01:53 UTC, kkkdeon commented on python/mlad/cli/validator/validators.py
> +        schema = yaml_parser.load(f)
이 부분은 다시 수정되었습니다

2022-01-27 02:23 UTC, JunhoeKim commented on python/mlad/cli/image.py
> +        COMMAND=f'CMD [{", ".join(commands)}]' if len(commands) > 0 else ''
이 부분에서 CMD가 아예 없을 경우에 base image의 CMD를 상속받도록하기 위해서는 빈 CMD로 덮어쓰면 안되는데 이에대한 처리는 이번 PR에서 하지 않는건가요?

2022-02-03 07:30 UTC, merged