Modify permission-related logic & delete deprecated code
onetop21/MLAppDeploy pull request #28
Opened 2021-08-12 09:42 UTC by kkkdeon

Resolves #27 

- 기존 Token 생성 및 인증, 사용 부분 삭제하였습니다. 
- mlad API 접근시 API에 따라 권한 체크하는 부분 삭제하였습니다.
  
- mlad config init시 session key를 생성하고, API 사용시 전달하도록 수정하였습니다. 
- service remove API / project remove API 은 session key를 확인해서 down 가능 여부 체크합니다. 

- Admin 권한은 kube context 여부(=kube config 여부)로 체크합니다. 
- (Admin) mlad API 내 node 관리부분을 삭제하고 client에서 직접하도록 수정하였습니다. 
- (Admin) project down 시 client에서 직접 수행하도록 수정하였습니다. 

+ top 기능 수정
- top cli로 제공하던 정보들 node cli/ project cli 에 통합했습니다. 
- mlad node resource / mlad ps / mlad ls

2021-08-13 08:42 UTC, JunhoeKim requested changes

2021-08-13 08:42 UTC, JunhoeKim commented on python/mlad/cli/libs/auth.py
> +        ctx = get_current_context()
ctx로 받아오지 않고 호출만 해도 될 것 같습니다.

2021-08-13 08:42 UTC, JunhoeKim commented on python/mlad/service/routers/project.py
> +                   swarm: bool = Query(True),
swarm option을 이제 안쓰게 된 것 같아서 정리해야 할 것 같습니다. 규모가 너무 크려나요

2021-08-13 08:42 UTC, JunhoeKim commented on python/mlad/service/routers/project.py
>      cli = ctlr.get_api_client()
여기도 마찬가지로 cli를 직접 호출하지 않고 내부에서 처리하도록 바꾸는게 좋아보입니다.

2021-08-13 09:28 UTC, kkkdeon commented on python/mlad/cli/libs/utils.py
> +    encode = jwt.encode(payload, "mlad", algorithm="HS256")\
네..

2021-08-17 02:43 UTC, kkkdeon commented on python/mlad/cli/libs/utils.py
>  ###############
그냥 구분선 같은데 효일님한테 여쭤봐야할 것 같습니다

2021-08-17 02:48 UTC, kkkdeon commented on python/mlad/cli/libs/utils.py
> +def get_username(session):
다르진 않은데 session에서 가져오는 그림이 맞는 것 같은데 고민이네요ㅠ

2021-08-17 05:11 UTC, JunhoeKim commented on python/mlad/cli/libs/utils.py
> +    encode = jwt.encode(payload, "mlad", algorithm="HS256")\
제가 hyppo에 `.flake8`에 설정해둔 셋팅이 있는데 이걸로 적용해서 다시 올려주실 수 있나요? 제가 봤을 때 너무 빡빡하다 싶은 옵션을 ignore 처리 했습니다.

2021-08-17 07:09 UTC, kkkdeon commented on python/mlad/cli/node.py
> +    cli = ctlr.get_api_client(get_k8s_config_path())
이 부분은 아직 고민이네요 저번에 얘기 했듯이 cli정의 부분 전역 변수 / 캐싱 하면 안될 것 같아서 ..

2021-08-17 15:08 UTC, kkkdeon commented on python/mlad/cli/libs/auth.py
> +def get_k8s_config_path():
현재 context로 가져오는 걸로 수정했습니다 !

2021-08-17 15:49 UTC, kkkdeon commented
+ config init 시 현재 config session이 존재하면 변경 여부를 물어보도록 추가하였습니다.

2021-08-18 03:52 UTC, kkkdeon commented on python/mlad/cli/node.py
> +    cli = ctlr.get_api_client(get_k8s_config_path())
반영했습니다!! 저 방식으로 바꿔나가면 될까요

2021-08-18 04:54 UTC, JunhoeKim commented
> * config init 시 현재 config session이 존재하면 변경 여부를 물어보도록 추가하였습니다.

어떤 상황인건가요? session을 변경해야할 이유가 있나요?

2021-08-18 04:56 UTC, JunhoeKim requested changes

2021-08-18 04:56 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +        if not isinstance(cli, client.api_client.ApiClient): raise \
\ 없이 raise를 블록 안으로 내리면 될 것 같습니다.

2021-08-18 04:56 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +def get_nodes(cli = None):
DEFAULT_CLI를 None 대신에 넣으면 되지 않을까요?

2021-08-18 05:59 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +def get_nodes(cli = None):
그렇네요 ;;;

2021-08-18 08:47 UTC, JunhoeKim approved these changes
LGTM

2021-08-18 08:50 UTC, merged