fix: mlad 환경 env가 user app env보다 우선순위가 높도록 수정
onetop21/MLAppDeploy pull request #288
Opened 2022-02-04 07:04 UTC by kkkdeon

Resolve #255 

- 환경변수가 중복으로 들어가지 않도록 수정
- 사용하지않는 docker service 관련 env 삭제

2022-02-04 11:44 UTC, JunhoeKim requested changes

2022-02-04 11:44 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +        env = [_create_V1Env(k, v).to_dict() for k, v in current.items()]
여기 update문에서도 새로 들어오는 env가 기존의 current를 덮어쓰는 방식인데 이러면 config_envs가 오염될 수 있지 않나요??

2022-02-04 11:44 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +                envs.append(_create_V1Env('INGRESS_PATH', ingress_path))
INGRESS_PATH는 사용되지 않는듯합니다.

2022-02-04 11:44 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +                envs.append(_create_V1Env('INGRESS_PATH', ingress_path))
이미 envs가 이용되고나서 추후에 envs에 append되는 것 같아요

2022-02-04 11:44 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +        app_envs['APP'] = name
이 5개의 대입문도 update문 하나로 대체하면 기존의 app_envs를 덮어쓴다는 의도가 더 잘 드러날 것 같아요
app_envs.update({'PROJECT': namespace_spec['project'] ...}) 이런 식으로요

2022-02-04 11:44 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +        value_from=client.V1EnvVarSource(
file_path와 value가 둘 다 none이 아니면 어떻게 동작하는거죠?

2022-02-07 06:42 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +        value_from=client.V1EnvVarSource(
V1EnvVar 객체를 사용할때 에러가 납니다 (정의할때 x)

2022-02-08 10:00 UTC, JunhoeKim requested changes

2022-02-08 10:00 UTC, JunhoeKim commented on python/mlad/cli/deploy.py
> +        env_checked = set()
여기 로직이 복잡한데, cli단에서 config_envs에 들어가면 env에서 delete 하고 시작하는 방법을 쓰면 어떤 문제가 있나요? ignore할 property를 지우고 시작하면 기존 로직을 그대로 쓸 수 있을 것 같아서요

2022-02-09 10:35 UTC, JunhoeKim approved these changes

2022-02-09 10:36 UTC, merged