resource api 내에서 project/app 단위 resource 모두 계산하도록 수정
onetop21/MLAppDeploy pull request #336
Opened 2022-02-25 12:50 UTC by kkkdeon

Resolve #330 #331 
- node cli 변수명 수정
- project resource api, cli, controller 수정
- node resource api, cli, controller 수정

- metric server unit 파싱 실패시 UnitError 반환

2022-02-28 03:45 UTC, JunhoeKim requested changes

2022-02-28 03:45 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +                    for k in res:
NotReady에 대한 처리도 그냥 서버에서 하도록 하고 metrics server 존재에 따라서 '-'로 뿌려주는 것도 서버에서 처리가 가능하지 않나요?

2022-02-28 03:45 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +                project_res[k] = round(project_res[k], 1)
round를 먼저하고 float(value) 값을 project_res[k]에 더해주면 round를 두 번 할 필요가 없는 것 같습니다.

2022-02-28 03:46 UTC, JunhoeKim commented
parse쪽을 일단 전체를 다 try, except로 묶고 오류가 발생하면 parse없이 원래 값을 그대로 띄우거나 '-' 값을 띄우도록 처리하는게 어떨까요?

2022-03-02 02:02 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +                project_res[k] = round(project_res[k], 1)
round를 한 값들을 더한 결과가 기존 값들을 더한 후에 round한 결과 값이랑 오차가 있을거라 이렇게 했는데 그렇게 진행하는게 나을까요

2022-03-02 02:03 UTC, kkkdeon commented on python/mlad/cli/project.py
> +                    for k in res:
서버에서 metric server 체크를 하도록 말씀이신가요 ??

2022-03-02 02:25 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +                project_res[k] = round(project_res[k], 1)
앗... 갑자기 고민되긴하는데 도연님이 맞다고 생각하는 방향으로 하시죠

2022-03-02 10:11 UTC, JunhoeKim approved these changes

2022-03-02 11:58 UTC, merged