pod status 가져오는 로직 수정
onetop21/MLAppDeploy pull request #362
Opened 2022-03-11 08:11 UTC by kkkdeon

Resolve #322

- pod status 가져오는 로직 수정
- constraints 버그 수정

2022-03-11 08:34 UTC, JunhoeKim requested changes

2022-03-11 08:34 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
>          return status
status라는 변수가 필요없이 맨 밑에는 'Running'을 return하면 될 것 같습니다.

2022-03-11 08:34 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +            elif container_status['state'] == 'Terminated':
completed를 count하는 방식이 가독성이 떨어진다고 느껴집니다.

detail을 계산하는 함수를 따로 빼고 (e.g., `_get_detail`)
container_status['state'] == 'Terminated' and detail != 'Completed' 하면 바로 return detail 하도록 바꾸고
if all([_get_detail(container) == 'Completed' for container in containers]):
   return 'Completed'
   
하는 방식으로 로직을 분리하는게 어떨까 싶어요.

2022-03-11 08:34 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
>      if pod.status.container_statuses:
if len(pod.status.container_statuses) > 0

2022-03-11 08:34 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +        pod_info['status'] = pod.status.conditions[0].reason if pod.status.conditions \
conditions의 length는 무조건 1인가요?

2022-03-11 08:34 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
>      def parse_status(containers):
typing이 필요합니다. detail이 nullable한 것 같은데 cli 쪽에서도 pod['status'] 가 None일 수 있다는 뜻 아닌가요?

2022-03-14 02:14 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +        pod_info['status'] = pod.status.conditions[0].reason if pod.status.conditions \
아니요 최신 condition 입니다

2022-03-14 05:42 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
>      def parse_status(containers):
detail이 none인 경우는 state가 Running 경우인데 cli쪽으로는 status로 Running일때는 Running, 그 외는 detail reason을 보내고 있기 때문에 사실상 None이 반환될 일이 없긴 합니다

2022-03-14 05:45 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
>      def parse_status(containers):
detail = 'Running' if container_status['state'] == 'Running' else container_status['detail']['reason']
와 같은 의미입니다

2022-03-14 05:52 UTC, JunhoeKim commented
추가적으로 `parse_status` 함수는 결과적으로 reason을 return하는 함수이므로 변수명을 detail로 둘게 아니라 reason으로 두는 것이 맞는 것 같습니다.

2022-03-14 06:36 UTC, JunhoeKim commented
mlad ls project.py 86 line에서 parse하는 부분에서 ['status']['state']가 아니라 ['status']를 직접 사용해야 합니다.

2022-03-14 06:46 UTC, JunhoeKim approved these changes

2022-03-14 06:50 UTC, merged