fix: k8s api exception 중복 로직 정리
onetop21/MLAppDeploy pull request #371
Opened 2022-03-14 11:02 UTC by kkkdeon

Resolve #353

2022-03-15 02:39 UTC, JunhoeKim requested changes

2022-03-15 02:39 UTC, JunhoeKim commented on python/mlad/core/exceptions.py
> +            name = args[0] if isinstance(args[0], str) else args[0].metadata.name
이게 항상 보장이 안되는 것 같습니다. update_k8s_namespace 함수만 해도요

2022-03-15 05:14 UTC, kkkdeon commented on python/mlad/core/exceptions.py
> +            name = args[0] if isinstance(args[0], str) else args[0].metadata.name
line 49 가 update_k8s namespace 를 위한 예외처리와 같습니다 .. 일단 지금 있는 함수들은 보장되도록 조건이 좀 들어가긴 했는데 일반화가 애매하긴하네요 이쪽이

2022-03-15 10:25 UTC, JunhoeKim requested changes

2022-03-15 10:25 UTC, JunhoeKim commented on python/mlad/core/exceptions.py
> +            if namespaced:
이거 이렇게만 처리하면 client.V1Namespace 처리 못하지 않나요?

2022-03-15 10:27 UTC, kkkdeon commented on python/mlad/core/exceptions.py
> +            if namespaced:
예외적인 케이스라 해당 데코레이터로 처리하지 않기로 했습니다

2022-03-15 10:36 UTC, JunhoeKim commented
mlad ps에서 metrics_server_running이 false인 경우 resources 변수 할당이 안되서 아래쪽에서 에러가 납니다.

2022-03-16 01:11 UTC, JunhoeKim approved these changes

2022-03-16 01:12 UTC, merged