project log app간 시간순 정렬 추가
onetop21/MLAppDeploy pull request #377
Opened 2022-03-18 05:12 UTC by kkkdeon

Resolve #327

- 불필요한 로직 삭제
- app 간 log 정렬을 위해 이미 쌓인 로그를 가져오는 로직과 이후 실시간으로 불러오는 로직 분리
- 정렬을 위해 기본적으로 k8s 로그에서 timestamp를 가져오고 옵션에 따라 반환 여부를 결정

commit log가 꼬여서 의미없는 commit이 좀 있습니다ㅜㅜ

2022-03-18 08:02 UTC, JunhoeKim requested changes

2022-03-18 08:02 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +                if 'stream' in msg:
stream을 검사할거면 timestamp와 target을 다 검사해야할 것 같고 그냥 if 문에 stopped를 먼저 처리하고 이 로직은 if 바깥으로 꺼내도 될 것 같아요 어차피 다른 input 형태가 들어올 가능성이 없으니까

2022-03-18 08:18 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +# ) -> client.V1Ingress:
오우 제 환경에서 버전 이슈로 잠시 지웠는데 까먹었네요 되돌리겠습니다

2022-03-18 08:27 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +                    since_seconds = since_seconds if since_seconds > 0 else 1
정확히는 since_seconds = 0 인 경우를 방지하기 위함입니다 (since_seconds가 0을 못받기 때문)
(현재로 부터 0.5초 이전의 로그부터 가져와라 -> since_seconds = 0.5 -> 불러올 수 없음 -> 최소값인 1로 변경)
since_seconds를 None으로 두면 처음부터 끝까지 다 가져와서 이렇게 했는데 지금 보니까 일단 가져와서 확인하면서 last timestamp 부터 다시 출력하게 해야하나 싶네요 .... 그런데 또 중간에 파싱하는 과정이 추가되면 stream 로그가 섞일까봐 우려가 되긴합니다

2022-03-18 08:30 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +        self.stacked_logs = PriorityQueue(maxsize=maxbuffer)
로그가 쌓이면서 pop되는 구조인데 pop되기 전에 한번에 65535가 쌓일 수도 있을까요? 어느정도로 하는게 좋을까요?

2022-03-18 08:34 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +        self.stacked_logs = PriorityQueue(maxsize=maxbuffer)
collect_logs 함수에서 전체를 다 put하기 때문에 pop하기전에 누락될 것 같습니다

2022-03-18 08:35 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +        self.stacked_logs = PriorityQueue(maxsize=maxbuffer)
max size 제한이 없어야하는게 맞지만 메모리 제한도 걸리고 애매하네요.. 일단 총 용량이 200MB가 되도록 제한해볼까요?

2022-03-18 08:36 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +        self.timestamps = timestamps
저도 고민인데 저희가 cli/ctlr쪽에서 timestamps를 bool 변수로 쓰고 있어서 통일하긴했습니다 is_timestamps? 이런식이 나을까요?

2022-03-18 08:45 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +        self.timestamps = timestamps
show_timestamp, use_timestamp 등등이 좋을 것 같은데요

2022-03-18 08:58 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +                if 'stream' in msg:
status 키가 없으면 무조건 stream msg 라고 가정한다 라는 얘기 맞을까요??

2022-03-18 09:25 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +        self.timestamps = timestamps
with_timestamp는 어떨까요 ??

2022-03-18 09:30 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +        self.stacked_logs = PriorityQueue(maxsize=maxbuffer)
그걸 미리 계산해서 qsize를 지정할 수 있나요 ??

2022-03-21 02:35 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +        self.stacked_logs = PriorityQueue(maxsize=maxbuffer)
음 다시 생각해보니까 좀 애매하군요.. string의 길이가 가변적이라

2022-03-21 02:36 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +                if 'stream' in msg:
네 맞습니다

2022-03-21 05:20 UTC, JunhoeKim requested changes

2022-03-21 05:20 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +            if self.stream is True:
`if self stream is True` -> `if self.steam`

2022-03-21 05:20 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
>          for _ in ([self.responses.get(resp)] if resp else list(self.responses.values())):
이 underscore 부분 처리 부탁드립니다.

2022-03-21 05:20 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
>                      pod = ev['object']['metadata']['name']
pod_name으로 명확하게 했으면 좋겠습니다. 그리고 한 가지 더 확인해보고 싶은게 scale down했을 때 해당 handler가 close가 되나요??? DELETED event가 발생하지 않고 제가 추가했던 deletionTimestamp만 생성되는 식으로 동작했던 것 같아서 handler close가 잘 안되었던 것 같습니다.

2022-03-21 05:20 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +                        for oid in [k for k, v in self.collector.thread_dict.items() if v['name'] == pod]:
그리고 object_Id를 쓰는게 이상합니다 .pod_name을 그냥 키로 쓰면 될 것 같아요.

2022-03-21 05:20 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +                    del self.thread_dict[object_id]
여기서 handler가 close 될 수 있어야하지 않을까요?

2022-03-21 05:20 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +                    del self.thread_dict[object_id]
아니면 get_stream_logs에서 본인이 본인 스스로 close를 할 수 있어도 될 것 같아요

2022-03-21 07:26 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +                        for oid in [k for k, v in self.collector.thread_dict.items() if v['name'] == pod]:
name을 key로 하게되면 if 'status' in msg 로직에서 문제가 생깁니다. 로그가 끝나고 큐에 stopped를 put할때 name을 넣어주기 애매하고 name을 stopped 아이템이 왔을 때 확인할 수 없어서요 
https://github.com/onetop21/MLAppDeploy/blob/a450eab23ededbe797e0ea194322e8b93f7ff8ec/python/mlad/core/kubernetes/logs.py#L117

2022-03-21 07:27 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
>                      pod = ev['object']['metadata']['name']
DELETED event는 발생합니다 확인해보니까 DELETED event가 발생했을 때 이미 thread dict에서 해당 아이템이 삭제되서 close가 안되었던 이슈같네요

2022-03-21 08:00 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +                        for oid in [k for k, v in self.collector.thread_dict.items() if v['name'] == pod]:
stopped msg에 똑같이 name을 넣어주면 되는거 아닌가요? _read_stream이 name argument를 받도록 하면 되고요

2022-03-21 09:48 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +                        for oid in [k for k, v in self.collector.thread_dict.items() if v['name'] == pod]:
iterable 을 돌면서 name을 가져오는 구조라 뭔가 어색하게 느껴졌습니다 argu로 넘기도록 하겠습니다

2022-03-22 02:34 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +        for name in names:
이거 name을 돌면서 안하고 name 당 로그 하나씩 다 받아서 와야겠는데요?

2022-03-22 06:58 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +            if all([True if len(logs_dict[name]) == 0 else False for name in names]):
`True if len(logs_dict[name]) == 0 else False` -> not log_dict[name]

2022-03-22 07:01 UTC, JunhoeKim commented on python/mlad/core/kubernetes/logs.py
> +                if len(logs) > 0 :
`if len(logs) > 0` -> `if logs`
https://peps.python.org/pep-0008/#programming-recommendations

저도 맨날 len() 붙여서 썼었는데 앞으로 고치려고요ㅜㅜ

2022-03-22 07:05 UTC, kkkdeon commented on python/mlad/core/kubernetes/logs.py
> +                if len(logs) > 0 :
허걱ㄷㄷ

2022-03-22 08:08 UTC, JunhoeKim approved these changes

2022-03-22 08:09 UTC, merged