Feature/config add update
onetop21/MLAppDeploy pull request #378
Opened 2022-03-21 04:49 UTC by onetop21

* get-env에 의해 registry, datstore(minio, mongodb) 설치 및 설치 정보 (status) 볼 수 있도록 수정
* mlad config add 시 get-env에 의해 설치된 registry, datastore 정보는 자동으로 가져오도록 수정
* mlad config add 기본 값을 admin으로 하고 user는 --address를 통해 무조건 endpoint를 입력하여 시작하도록 변경

2022-03-21 06:00 UTC, JunhoeKim requested changes

2022-03-21 06:00 UTC, JunhoeKim commented on python/mlad/core/docker/controller.py
> +    from mlad.cli.config import get as get_config
core 패키지에서 cli 패키지를 import하는 역방향이 이상한 것 같습니다. get_cli의 호출부에서 올바른 host를 강제로 넣게 해야 할 것 같습니다.

2022-03-21 06:20 UTC, onetop21 commented on python/mlad/cli/config_cli.py
> +@click.option('--address', required=False, help='Endpoint to connect MLAppDeploy API server.')
어차피  context를 입력할 때 address를 모르면 안되니까요?

2022-03-21 06:22 UTC, onetop21 commented on python/mlad/cli/config.py
> +    if not address:
if address is None: 이 되면 될까요?

2022-03-21 06:23 UTC, onetop21 commented on python/mlad/cli/config.py
> +            raise Exception("Cannot find kubeconfig file.")
수정 조치하겠습니다. :)

2022-03-21 06:23 UTC, onetop21 commented on python/mlad/cli/config.py
> +from mlad.core.kubernetes import controller as kubectlr
수정 조치하겠습니다. :)

2022-03-21 06:24 UTC, onetop21 commented on python/mlad/cli/config.py
> +                               default=f'http://{address}')
... 이건 삭제하는게 맞겠네요

2022-03-21 06:24 UTC, onetop21 commented on python/mlad/cli/config.py
> +    import re
Okay

2022-03-21 06:25 UTC, onetop21 commented on python/mlad/cli/config.py
> +            raise ValueError(f"Docker Host[{spec['docker_host']}] is not valid.")
적당한 Exception이 뭐가 있을까요?

2022-03-21 06:27 UTC, onetop21 commented on python/mlad/cli/config.py
> +    spec['docker_host'] = utils.prompt('An Endpoint of Docker Host', default=default_docker_host)
> 이건 config들과 상관없이 글로벌하게 관리해야해서 따로 두시는거죠?

이해하지 못하였습니다. Registry, Datastore 를 가져오는 docker를 명확하게 알려주기 위해 Docker Host 관리도 추가하였습니다.

2022-03-21 06:28 UTC, onetop21 commented on python/mlad/cli/config.py
> +    spec['docker_host'] = utils.prompt('An Endpoint of Docker Host', default=default_docker_host)
> 그럼 이미 'docker_host'가 spec에 저장되어있는 경우에도 매번 물어보고 덮어쓰나요?

... Config에 대해 제가 제대로 이해하지 못했었나보네요. ㅎㅎ Context 밑으로 이동하겠습니다.

2022-03-21 06:29 UTC, onetop21 commented on python/mlad/cli/config.py
> +        group = pattern.match(spec['docker_host'])
옛날 코드가 남아있있네요.

2022-03-21 06:29 UTC, onetop21 commented on python/mlad/cli/config.py
> +        DOCKER_IP = f'{ip}'
IP, port, scheme 등을 붙일려다가 말았습니다만, f-string 속도는 빨라서 뭐 큰 이슈는 없지 않을까요?

2022-03-21 06:32 UTC, onetop21 commented on python/mlad/core/docker/controller.py
> +    from mlad.cli.config import get as get_config
처음엔 그렇게 했는데, controller 내에서 get_cli를 호출하는 부 까지 모두 수정할 방법이 없어서 저렇게 했습니다.
혹시 다른 대안이 있을까요?
어차피 docker controller는 cli에서만 사용하기 때문에 문제 없을것 같아서 저렇게 했습니다.

2022-03-21 06:33 UTC, onetop21 commented on python/mlad/cli/config.py
> +    if not address:
if address is None: ...

2022-03-21 06:34 UTC, onetop21 commented on python/mlad/cli/config.py
> +    import requests
Okay

2022-03-21 06:44 UTC, onetop21 commented on python/mlad/cli/config.py
> +        elif not DOCKER_IP:
굳이 타지 않아도 되는 분기를 태울 필요는 없다고 판단했습니다만, 
원하시면 그렇게 수정하도록 하겠습니다.

2022-03-21 07:00 UTC, JunhoeKim commented on python/mlad/core/docker/controller.py
> +    from mlad.cli.config import get as get_config
아 그러네요.. docker controller 내부에서도 호출을 계속하는구나.. 결국 큰 흐름으로 봤을 때는 docker controller는 cli쪽으로 이동하는게 맞을 수도 있겠네요. cli 안에서만 노니까

2022-03-21 07:01 UTC, JunhoeKim commented on python/mlad/cli/config_cli.py
> +@click.option('--address', required=False, help='Endpoint to connect MLAppDeploy API server.')
어차피 context 입력에서 막힌다는 뜻이지요?

2022-03-21 07:11 UTC, onetop21 commented on python/mlad/core/docker/controller.py
> +    from mlad.cli.config import get as get_config
일단, 여기다 두고 추후 cli로 이동하는것으로 하시죠 :)

2022-03-21 07:59 UTC, onetop21 commented on python/mlad/cli/config_cli.py
> +@click.option('--address', required=False, help='Endpoint to connect MLAppDeploy API server.')
그렇죠. address를 알아야 정상 설정할테니까요 :)

2022-03-21 12:30 UTC, JunhoeKim requested changes

2022-03-21 12:30 UTC, JunhoeKim commented on python/mlad/cli/config.py
> +    if container_list:
`port_bindings = container_list[0].attrs['HostConfig']['PortBindings']`
SERVER_PORT = pord_bindings['9000/tcp'][0]

으로 변수를 쪼개는게 더 좋아보입니다.

2022-03-21 12:30 UTC, JunhoeKim commented on python/mlad/cli/config.py
> +        ACCESS_KEY = [_ for _ in container_list[0].attrs['Config']['Env'] if _.startswith('MINIO_ACCESS_KEY=')]
container_list[0].attrs['Config']['Env']도 마찬가지로요

2022-03-21 12:30 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +def get_contexts(config_file: str = f'{Path.home()}/.kube/config') -> Tuple[List[Dict | List | Any], Any]:
python3.7에서 Generic에 |가 지원이 안되는 것 같습니다.

2022-03-21 12:30 UTC, JunhoeKim commented on python/mlad/cli/config.py
> +        if requests.get(f'http://{ip}:25000/v2/_catalog', timeout=1):
이 단계에서 ConnectionRefusedError가 발생합니다.

2022-03-21 12:30 UTC, JunhoeKim commented on python/mlad/cli/config.py
> +    elif requests.get(f'http://{address}', timeout=1):
address가 http가 포함되서 들어오는 경우에 대한 처리가 안되어있습니다. 또한 정상 연결이 되는 경우 NotFound 에러가 발생하는데 이 때 implicit하게 bool 값이 False가 되서 무조건 InvalidURLError를 타게 되어있습니다. 그리고 잘못된 주소가 뜨는 경우 ConnectionError가 발생하는데 이에 대한 예외 처리도 따로 필요합니다. 이에 대한 예외처리는 `mlad.api.exceptions`에 ConnectionRefusedError가 있습니다.

2022-03-21 12:30 UTC, JunhoeKim commented on python/mlad/cli/config.py
> +        # address = utils.prompt('MLAD API Server Address',
주석 삭제부탁드립니다.

2022-03-21 12:30 UTC, JunhoeKim commented on python/mlad/cli/config.py
> +        raise InvalidURLError
해당 오류에 메시지가 담겨야 할 것 같습니다.

2022-03-22 01:25 UTC, JunhoeKim commented on python/mlad/cli/config.py
> +        PORT_BINDINGS = container_list[0].attrs['HostConfig']['PortBindings']
대문자를 활용한 snakecase를 현재까지는 static constant에 해당하는 변수만 사용했었는데 어떤 convention을 가지고 가는게 좋을까요??

2022-03-22 02:07 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +def get_contexts(config_file: str = f'{Path.home()}/.kube/config') -> Tuple[List[Dict | List | Any], Any]:
Union[Dict, List, Any]

2022-03-22 02:11 UTC, JunhoeKim approved these changes

2022-03-22 02:31 UTC, merged