Implement the interface of context APIs
onetop21/MLAppDeploy pull request #44
Opened 2021-08-19 05:19 UTC by JunhoeKim

Resolves #35 

각 context 기능에 대한 CLI를 구현했습니다.

`controller.py`의 flake8 linting을 일부 수정했습니다 (엄청 많이 남았습니다)

2021-08-19 07:43 UTC, kkkdeon requested changes

2021-08-19 07:43 UTC, kkkdeon commented on python/mlad/cli/context_cli.py
> +    context.delete(name)
현재 context 삭제하려고하면 에러가 raise 되는데 msg만 보이게 하면 좋을 것 같습니다.

2021-08-19 07:43 UTC, kkkdeon commented on python/mlad/cli/context_cli.py
> +    click.echo(OmegaConf.to_yaml(ret))
이 부분 삭제해야할 것 같습니다 (cli 쪽에서 echo)

2021-08-19 07:43 UTC, kkkdeon commented on python/mlad/cli/context_cli.py
> +def set(name, args):
이 부분 갑자기 (원하는 context로 이동후) mlad context set args이 나을지
지금처럼 특정 context name 지정하는 식이 나을지 고민되네요

2021-08-19 07:45 UTC, kkkdeon requested changes

2021-08-19 07:45 UTC, kkkdeon commented on python/mlad/cli/context_cli.py
> +    ret = context.get(name)
context.get 내에서 한번더 echo 하네요!!

2021-08-19 08:24 UTC, JunhoeKim commented on python/mlad/cli/context_cli.py
> +def set(name, args):
흠 일단 이렇게 가고 효일님 피드백을 받을까요?

2021-08-19 08:24 UTC, JunhoeKim commented on python/mlad/cli/context_cli.py
> +    context.delete(name)
근데 저희 다른 에러들도 다 stacttrace + 에러로 보이게하지 않나요?

2021-08-19 08:25 UTC, JunhoeKim commented on python/mlad/cli/context_cli.py
> +    ret = context.get(name)
수정하겠습니다

2021-08-20 05:48 UTC, kkkdeon approved these changes

2021-08-20 05:49 UTC, merged