Feature/issue-49 : Modify project & service modules based on reformed schema
onetop21/MLAppDeploy pull request #59
Opened 2021-08-30 10:34 UTC by kkkdeon

Resolve #49

- 변경된 schema 에 맞춰, kind에 따라 app (기존 service)들을 실행할 수 있도록 project/service수정
    1. mlad service api와 controller에서 service 관련 api들이 수정되었습니다. service 생성시 kind에 따라 _create api 들을 옵션에 
      맞게 사용합니다.
    2. 내부적으로 실제 app의 kind(App, Service, Job) 은 KIND, app을 구동하는 kube kind는 CONTROLLER 라는 변수명(+label) 을 
    사용합니다 
    3. 지금은 deploy를 고려하지 않는데, 이후에 project 와 deploy를 구별하기 위해 type등을 추가할 예정입니다. 
    4. mlad project init 변경 (변경된 schema 적용)
    5. examples/project 예제 동작O
    
- validator 적용 
    1. dir 위치가 조금 고민되네요. editor도 추가될 예정이라 일단 임시로 저렇게 두었습니다. 
    2. project가 직접적으로 사용하는건 project_validator.validate
    3. 현재 validator error msg가 문제 파악이 어려운 이슈가 있어서 이후 수정이 필요할 것 같습니다. (일단 지금은 출력)
    4. validator가 추가되면서 기존에 default format들 (mlad/core/default/*) 가 불필요하다고 생각되어 일단 사용하지 않습니다.
 
TODO
- Autoscaler test 를 추가적으로 할 예정입니다(동작은 합니다.)
- validator에서 command/args type이 str -> [str, list]로 바뀌어서 수정할 예정입니다.

2021-08-30 10:54 UTC, JunhoeKim commented on examples/project/mlad-project.yml
> +        kind: App                  # [OPTIONAL] Describe kind of app. (*App, Job, Service)
App이 default라 kind에 안넣으셔도 되는데 일부러 넣으신거죠?

2021-08-30 11:19 UTC, kkkdeon commented on examples/project/mlad-project.yml
> +        kind: App                  # [OPTIONAL] Describe kind of app. (*App, Job, Service)
넵넵

2021-09-03 00:47 UTC, JunhoeKim requested changes

2021-09-08 03:28 UTC, JunhoeKim commented on python/mlad/service/routers/project.py
>              for _ in gen:
네 모두 바꾸는게 좋아보입니다.

2021-09-08 03:32 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +        res = api.project.create(base_labels, extra_envs, credential=credential, allow_reuse=False)
아 프로젝트를 올리고나서 서비스를 덮어쓸 수 있는 기능이 있는건가요?

2021-09-08 03:33 UTC, JunhoeKim commented on python/mlad/cli/validator/yaml_validator.py
> +            self._error(validator._errors)
혹시 이 부분이 어떤 처리인지 설명을 들을 수 있을까요?

2021-09-08 03:35 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +                res = resources[inspect['name']].copy()
뒤에 resources[inspect['name']]을 참조하여 쓰는 코드가 따로 없다면 상관없지 않나요??

2021-09-08 04:52 UTC, JunhoeKim requested changes

2021-09-08 04:52 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +    core_api = client.CoreV1Api(cli)
api, core_api가 겹칩니다

2021-09-08 04:52 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +            if type == 'cpu': requests['cpu'] = str(resources['cpu']) if resources[type] else None
flake8 기준으로는 아래 들여쓰기를 해야 하는 부분인데 저희 flake8 기준으로 가기로 했었나요? 그리고 elif를 쓰는게 더 맞는 것 같습니다 (if를 연속으로 쓰는 것 보다는)

2021-09-08 04:52 UTC, JunhoeKim commented on python/mlad/core/kubernetes/controller.py
> +            if controller == 'Job':
이렇게 if문으로 쪼개서 처리하는 로직이 많은데, 나중에 클래스로 분리하면 클래스 정의할 때만 if문을 넣고 모든 뒷 처리는 controller.delete() 방식으로 처리 할 수 있으면 코드가 훨씬 깔끔해질 것 같긴합니다..

2021-09-08 04:52 UTC, JunhoeKim commented on python/mlad/service/routers/service.py
> +def service_inspect(project_key:str, service_name:str,
이것도 원래 `동사_명사` 순서로 메소드 이름은 오는게 맞는데 다음에 한 번에 고칩시다

2021-09-08 04:52 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +    cli = ctlr.get_api_client()
이 부분을 따로 처리하는 이유를 이해를 못해서 부연설명해주실 수 있을까요?

2021-09-08 04:52 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +        except APIError as e:
여러 workload를 생성하는 과정에서 중간에 exception이 나면 checkpoint 설정을 헀다가 rollback을 해주는 로직은 있어야 할 것 같은데 이슈로 남겨두고 다음에 하는게 어떨까요?

2021-09-08 05:37 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +            if type == 'cpu': requests['cpu'] = str(resources['cpu']) if resources[type] else None
flake8 걸리는 부분이 if type == 'cpu': 이부분 말씀이신가요???

2021-09-08 05:43 UTC, kkkdeon commented on python/mlad/cli/project.py
> +    cli = ctlr.get_api_client()
오우 이 부분 빼게될 것 같습니다 run 부분이 제가 착각해서 아직 구현이 덜 되었습니다

2021-09-08 05:43 UTC, kkkdeon commented on python/mlad/cli/project.py
> +        except APIError as e:
넵 이슈로 남겨두겠습니다

2021-09-08 05:45 UTC, kkkdeon commented on python/mlad/cli/project.py
> +        res = api.project.create(base_labels, extra_envs, credential=credential, allow_reuse=False)
덮어쓰진 못하고 다른 서비스를 추가했을 경우입니다

2021-09-08 05:55 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +        for name, service, node, phase, status, restart_cnt, uptime, ports, mem, cpu, gpu in task_info:
tuple이 element이기 때문에 pod name으로 정렬되는게 의도가 맞나요?

2021-09-08 05:57 UTC, JunhoeKim commented on python/mlad/cli/project.py
> +                res = resources[inspect['name']].copy()
resources[inspect['name']]을 재참조하지 않는한 상관없는게 아닌가요?

2021-09-08 05:59 UTC, kkkdeon commented on python/mlad/cli/project.py
> +                res = resources[inspect['name']].copy()
한 service내 task가 여러 개이면 for문을 돌때 resources[inspect['name']]을 반복 참조하는 경우가 있을 수 있습니다

2021-09-08 06:00 UTC, kkkdeon commented on python/mlad/core/kubernetes/controller.py
> +            if controller == 'Job':
음 이부분도 이슈로 따로 남겨두겠습니다

2021-09-08 08:14 UTC, kkkdeon commented on python/mlad/cli/project.py
> +        for name, service, node, phase, status, restart_cnt, uptime, ports, mem, cpu, gpu in task_info:
넵넵 service name 정렬이 목적입니다 (x[1] => service)

2021-09-09 10:22 UTC, merged